language: node_js
node_js:
  - '0.10'
notifications:
  email: false
env:
  global:
  - secure: Fqpk3NE1UCWnSeYrNAZSxxL9JBK7DtcV6pmjcut2lAGiLyXF67cd8Hmnw/HeK7u7ak/troYsfvKerl+p1TkUf1JZB4aA5V9FEbkLK7ZKQxIcCvwaoFGlRxaOHwcVO7ZuKOfZFV/tHDcWrweN+Vlcf/sShOd1l9DgyaTLZCBLf/8=
  - secure: CbO0xtC3D0umg9Ii2EWjnVmZEgJ3rN/Y7Vbj06YdxAJuoT2+kCKzOmSgUWVU3iN0jjU3iUfeC4WXiTAIkCSwzNAdQhdoJ6gUEm26rwlfazolPu9uAYhHIg+RxUShtuHwqbz16e1IFyOmtZbWVyqs7XTxywmLi957tDFt798uIrs=
after_success: "find public -exec curl --ftp-create-dirs -T {} -v ftp://$USER:$FTP_PASSWORD@braveux.com/public_html/dev/ \;"